# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camsetting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_Cam(object):
    def setupUi(self, Ui_MainWindow_Cam):
        Ui_MainWindow_Cam.setObjectName("MainWindow")
        Ui_MainWindow_Cam.resize(728, 600)
        Ui_MainWindow_Cam.setStyleSheet("border-image: url(:/ui_img/background.jpg);")
        self.centralwidget = QtWidgets.QWidget(Ui_MainWindow_Cam)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("border-image: url(:/ui_img/cam_setting.png);")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setStyleSheet("border-image: url(:/ui_img/trans.png);")
        self.widget_2.setObjectName("widget_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(20, 80, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(189,215,238);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(189,215,238);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(20, 200, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(189,215,238);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(20, 272, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(189,215,238);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(20, 322, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(189,215,238);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(20, 395, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(189,215,238);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(20, 445, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(189,215,238);")
        self.label_7.setObjectName("label_7")
        self.comboBox_model = QtWidgets.QComboBox(self.widget_2)
        self.comboBox_model.setGeometry(QtCore.QRect(100, 90, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(16)
        self.comboBox_model.setFont(font)
        self.comboBox_model.setAutoFillBackground(False)
        self.comboBox_model.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(68,114,196);\n"
"color: rgb(255,255,255);")
        self.comboBox_model.setFrame(True)
        self.comboBox_model.setObjectName("comboBox_model")
        self.comboBox_model.addItem("")
        self.textEdit_Exposure = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit_Exposure.setGeometry(QtCore.QRect(140, 157, 91, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        self.textEdit_Exposure.setFont(font)
        self.textEdit_Exposure.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255,255,255);")
        self.textEdit_Exposure.setObjectName("textEdit_Exposure")
        self.textEdit_Focus = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit_Focus.setGeometry(QtCore.QRect(140, 206, 91, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        self.textEdit_Focus.setFont(font)
        self.textEdit_Focus.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255,255,255);")
        self.textEdit_Focus.setObjectName("textEdit_Focus")
        self.textEdit_Crop_W = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit_Crop_W.setGeometry(QtCore.QRect(140, 277, 91, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        self.textEdit_Crop_W.setFont(font)
        self.textEdit_Crop_W.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255,255,255);")
        self.textEdit_Crop_W.setObjectName("textEdit_Crop_W")
        self.textEdit_Crop_H = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit_Crop_H.setGeometry(QtCore.QRect(140, 329, 91, 40))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        self.textEdit_Crop_H.setFont(font)
        self.textEdit_Crop_H.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255,255,255);")
        self.textEdit_Crop_H.setObjectName("textEdit_Crop_H")
        self.horizontalSlider_Exposure = QtWidgets.QSlider(self.widget_2)
        self.horizontalSlider_Exposure.setGeometry(QtCore.QRect(250, 165, 331, 22))
        self.horizontalSlider_Exposure.setMinimum(1)
        self.horizontalSlider_Exposure.setMaximum(13)
        self.horizontalSlider_Exposure.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Exposure.setObjectName("horizontalSlider_Exposure")
        self.horizontalSlider_Focus = QtWidgets.QSlider(self.widget_2)
        self.horizontalSlider_Focus.setGeometry(QtCore.QRect(250, 215, 331, 22))
        self.horizontalSlider_Focus.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Focus.setObjectName("horizontalSlider_Focus")
        self.horizontalSlider_Crop_W = QtWidgets.QSlider(self.widget_2)
        self.horizontalSlider_Crop_W.setGeometry(QtCore.QRect(250, 285, 331, 22))
        self.horizontalSlider_Crop_W.setMaximum(100)
        self.horizontalSlider_Crop_W.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Crop_W.setObjectName("horizontalSlider_Crop_W")
        self.horizontalSlider_Crop_H = QtWidgets.QSlider(self.widget_2)
        self.horizontalSlider_Crop_H.setGeometry(QtCore.QRect(250, 337, 331, 22))
        self.horizontalSlider_Crop_H.setMaximum(100)
        self.horizontalSlider_Crop_H.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Crop_H.setObjectName("horizontalSlider_Crop_H")
        self.checkBox_Auto_Exposure = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_Auto_Exposure.setGeometry(QtCore.QRect(600, 160, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(16)
        self.checkBox_Auto_Exposure.setFont(font)
        self.checkBox_Auto_Exposure.setStyleSheet("color: rgb(189,215,238);")
        self.checkBox_Auto_Exposure.setObjectName("checkBox_Auto_Exposure")
        self.checkBox_Auto_Focus = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_Auto_Focus.setGeometry(QtCore.QRect(600, 210, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(16)
        self.checkBox_Auto_Focus.setFont(font)
        self.checkBox_Auto_Focus.setStyleSheet("color: rgb(189,215,238);")
        self.checkBox_Auto_Focus.setObjectName("checkBox_Auto_Focus")
        self.checkBox_11Crop = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_11Crop.setGeometry(QtCore.QRect(600, 280, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(16)
        self.checkBox_11Crop.setFont(font)
        self.checkBox_11Crop.setStyleSheet("color: rgb(189,215,238);")
        self.checkBox_11Crop.setObjectName("checkBox_11Crop")
        self.radioButton_90 = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_90.setGeometry(QtCore.QRect(270, 410, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(16)
        self.radioButton_90.setFont(font)
        self.radioButton_90.setStyleSheet("color: rgb(189,215,238);")
        self.radioButton_90.setObjectName("radioButton_90")
        self.radioButton_0 = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_0.setGeometry(QtCore.QRect(140, 410, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(16)
        self.radioButton_0.setFont(font)
        self.radioButton_0.setStyleSheet("color: rgb(189,215,238);")
        self.radioButton_0.setObjectName("radioButton_0")
        self.radioButton_180 = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_180.setGeometry(QtCore.QRect(400, 410, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(16)
        self.radioButton_180.setFont(font)
        self.radioButton_180.setStyleSheet("color: rgb(189,215,238);")
        self.radioButton_180.setObjectName("radioButton_180")
        self.radioButton_270 = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_270.setGeometry(QtCore.QRect(530, 410, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(16)
        self.radioButton_270.setFont(font)
        self.radioButton_270.setStyleSheet("color: rgb(189,215,238);")
        self.radioButton_270.setObjectName("radioButton_270")
        self.checkBox_Horizontal = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_Horizontal.setGeometry(QtCore.QRect(270, 455, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(16)
        self.checkBox_Horizontal.setFont(font)
        self.checkBox_Horizontal.setStyleSheet("color: rgb(189,215,238);")
        self.checkBox_Horizontal.setObjectName("checkBox_Horizontal")
        self.checkBox_Vertical = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_Vertical.setGeometry(QtCore.QRect(140, 455, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(16)
        self.checkBox_Vertical.setFont(font)
        self.checkBox_Vertical.setStyleSheet("color: rgb(189,215,238);")
        self.checkBox_Vertical.setObjectName("checkBox_Vertical")
        self.pushButton_Run = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_Run.setGeometry(QtCore.QRect(460, 510, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(18)
        self.pushButton_Run.setFont(font)
        self.pushButton_Run.setStyleSheet("\n"
"\n"
"QPushButton\n"
"{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: rgb(189,215,238);\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgba(189,215,238, 150);\n"
"    color: rgb(189,215,238);\n"
"}\n"
"\n"
"")
        self.pushButton_Run.setObjectName("pushButton_Run")
        self.pushButton_Stop = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_Stop.setGeometry(QtCore.QRect(580, 510, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(18)
        self.pushButton_Stop.setFont(font)
        self.pushButton_Stop.setStyleSheet("\n"
"\n"
"QPushButton\n"
"{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: rgb(189,215,238);\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgba(189,215,238, 150);\n"
"    color: rgb(189,215,238);\n"
"}\n"
"\n"
"")
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.horizontalLayout.addWidget(self.widget_2)
        self.verticalLayout_4.addWidget(self.widget)
        Ui_MainWindow_Cam.setCentralWidget(self.centralwidget)

        self.retranslateUi(Ui_MainWindow_Cam)
        QtCore.QMetaObject.connectSlotsByName(Ui_MainWindow_Cam)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CNN Template"))
        self.label.setText(_translate("MainWindow", "Device"))
        self.label_2.setText(_translate("MainWindow", "Exposure"))
        self.label_3.setText(_translate("MainWindow", "Focus"))
        self.label_4.setText(_translate("MainWindow", "Crop Width"))
        self.label_5.setText(_translate("MainWindow", "Crop Height"))
        self.label_6.setText(_translate("MainWindow", "Rotation"))
        self.label_7.setText(_translate("MainWindow", "Flip"))
        self.comboBox_model.setItemText(0, _translate("MainWindow", "Device0"))
        self.textEdit_Exposure.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Dubai\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.textEdit_Focus.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Dubai\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.textEdit_Crop_W.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Dubai\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.textEdit_Crop_H.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Dubai\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.checkBox_Auto_Exposure.setText(_translate("MainWindow", "Auto"))
        self.checkBox_Auto_Focus.setText(_translate("MainWindow", "Auto"))
        self.checkBox_11Crop.setText(_translate("MainWindow", "1:1 Crop"))
        self.radioButton_90.setText(_translate("MainWindow", "90°"))
        self.radioButton_0.setText(_translate("MainWindow", "0°"))
        self.radioButton_180.setText(_translate("MainWindow", "180°"))
        self.radioButton_270.setText(_translate("MainWindow", "270°"))
        self.checkBox_Horizontal.setText(_translate("MainWindow", "Horizontal"))
        self.checkBox_Vertical.setText(_translate("MainWindow", "Vertical"))
        self.pushButton_Run.setText(_translate("MainWindow", "Run"))
        self.pushButton_Stop.setText(_translate("MainWindow", "Stop"))
import pic
